In [1]:
import pandas as pd
import numpy as np
from sklearn import tree, metrics
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
from io import StringIO  
from IPython.display import Image  
!pip install pydotplus 
import pydotplus 
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import datetime

Requirement already satisfied: pydotplus in /opt/anaconda3/lib/python3.8/site-packages (2.0.2)
Requirement already satisfied: pyparsing>=2.0.1 in /opt/anaconda3/lib/python3.8/site-packages (from pydotplus) (2.4.7)

In [2]:
df2 = pd.read_excel(r'/Users/markclampitt/Documents/Springboard/Capstone2/Data\new_df.xlsx')

In [3]:
df2.head()

,Home Team Spread_x,Away Team Spread_x,Total_x,Rolling 5 Past H&A Score_Home_Team,Rolling 5 Past H&A Score Avg_Home_Team,Rolling 5 Past H&A 1st Downs_Home_Team,Rolling 5 Past H&A 1st Downs Avg_Home_Team,Rolling 5 Past H&A Total Yards_Home_Team,Rolling 5 Past H&A Total Yards Avg_Home_Team,Rolling 5 Past H&A Yards per Pass_Home_Team,...,Rolling 5 Past H&A Conf T Losses_Home_Team,Rolling 5 Past H&A Conf T Losses_Away_Team,Rolling 5 Past H&A Season T Losses_Home_Team,Rolling 5 Past H&A Season T Losses_Away_Team,Away Score_x_x,Home Score_x_x,Home Team,Away Team,Year,Date
0,-2.5,2.5,52.0,172.0,34.4,119.0,23.8,2211.0,442.2,46.6,...,0.0,5.0,1.0,5.0,NaN,NaN,Georgia,Alabama,2022,2022-01-10
1,6.5,-6.5,49.0,187.0,37.4,118.0,23.6,2484.0,496.8,49.3,...,5.0,0.0,5.0,0.0,24.0,41.0,Alabama,Georgia,2021,2021-12-04
2,6.5,-6.5,27.0,114.0,22.8,100.0,20.0,1791.0,358.2,30.9,...,16.0,11.0,21.0,11.0,24.0,27.0,LSU,Texas A&M,2021,2021-11-27
3,19.5,-19.5,55.5,123.0,24.6,111.0,22.2,1998.0,399.6,38.5,...,11.0,5.0,16.0,5.0,24.0,22.0,Auburn,Alabama,2021,2021-11-27
4,31.5,-31.5,63.5,88.0,17.6,81.0,16.2,1569.0,313.8,31.4,...,25.0,13.0,35.0,18.0,45.0,21.0,Vanderbilt,Tennessee,2021,2021-11-27

In [4]:
df2.shape

(977, 41)

In [5]:
df2.describe()

,Home Team Spread_x,Away Team Spread_x,Total_x,Rolling 5 Past H&A Score_Home_Team,Rolling 5 Past H&A Score Avg_Home_Team,Rolling 5 Past H&A 1st Downs_Home_Team,Rolling 5 Past H&A 1st Downs Avg_Home_Team,Rolling 5 Past H&A Total Yards_Home_Team,Rolling 5 Past H&A Total Yards Avg_Home_Team,Rolling 5 Past H&A Yards per Pass_Home_Team,...,Previous H&A Ranking_Home_Team,Home Team Ranking_x,Away Team Ranking_x,Rolling 5 Past H&A Conf T Losses_Home_Team,Rolling 5 Past H&A Conf T Losses_Away_Team,Rolling 5 Past H&A Season T Losses_Home_Team,Rolling 5 Past H&A Season T Losses_Away_Team,Away Score_x_x,Home Score_x_x,Year
count,977.000000,977.000000,977.000000,942.000000,942.000000,936.000000,936.000000,936.000000,936.000000,936.000000,...,970.000000,977.000000,977.000000,942.000000,942.000000,942.000000,942.000000,976.000000,976.000000,977.000000
mean,-2.826510,2.826510,51.393040,127.528662,25.505732,98.152778,19.630556,1861.628205,372.325641,36.112393,...,57.764948,58.841351,57.990788,11.301486,11.207006,13.464968,13.378981,24.196721,26.869877,2012.903787
std,13.250883,13.250883,8.025355,42.490716,8.498143,17.727442,3.545488,378.047707,75.609541,7.377706,...,44.523697,44.375891,44.404771,6.881599,6.842748,8.498693,8.388907,13.896771,13.421241,5.187959
min,-41.500000,-36.000000,27.000000,33.000000,6.600000,47.000000,9.400000,957.000000,191.400000,18.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2004.000000
25%,-12.500000,-6.500000,45.500000,98.000000,19.600000,87.000000,17.400000,1600.750000,320.150000,31.200000,...,10.000000,11.000000,11.000000,6.000000,5.000000,7.000000,7.000000,14.000000,17.000000,2008.000000
50%,-3.000000,3.000000,50.500000,124.000000,24.800000,97.000000,19.400000,1857.000000,371.400000,35.700000,...,99.000000,99.000000,99.000000,11.000000,11.000000,13.000000,13.000000,23.000000,26.000000,2013.000000
75%,6.500000,12.500000,56.000000,152.000000,30.400000,110.000000,22.000000,2109.250000,421.850000,40.800000,...,99.000000,99.000000,99.000000,16.000000,16.000000,19.000000,19.000000,34.000000,37.000000,2017.000000
max,36.000000,41.500000,82.500000,261.000000,52.200000,155.000000,31.000000,2987.000000,597.400000,64.300000,...,99.000000,99.000000,99.000000,35.000000,31.000000,40.000000,40.000000,72.000000,74.000000,2022.000000

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 41 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Home Team Spread_x                               977 non-null    float64
 1   Away Team Spread_x                               977 non-null    float64
 2   Total_x                                          977 non-null    float64
 3   Rolling 5 Past H&A Score_Home_Team               942 non-null    float64
 4   Rolling 5 Past H&A Score Avg_Home_Team           942 non-null    float64
 5   Rolling 5 Past H&A 1st Downs_Home_Team           936 non-null    float64
 6   Rolling 5 Past H&A 1st Downs Avg_Home_Team       936 non-null    float64
 7   Rolling 5 Past H&A Total Yards_Home_Team         936 non-null    float64
 8   Rolling 5 Past H&A Total Yards Avg_Home_Team     936 non-null    float64
 9   Rolling 5 Past H&A Yards per Pass_Home_Team      936 non-null    float64
 10  Rolling 5 Past H&A Yards per Pass Avg_Home_Team  936 non-null    float64
 11  Rolling 5 Past H&A Spread_Home_Team              942 non-null    float64
 12  Rolling 5 Past H&A Spread Avg_Home_Team          942 non-null    float64
 13  Rolling 5 Past H&A Spread Min_Home_Team          942 non-null    float64
 14  Rolling 5 Past H&A Score_Away_Team               942 non-null    float64
 15  Rolling 5 Past H&A Score Avg_Away_Team           942 non-null    float64
 16  Rolling 5 Past H&A Score Max_Away_Team           942 non-null    float64
 17  Rolling 3 Past H&A Score_Away_Team               956 non-null    float64
 18  Rolling 3 Past H&A Score Avg_Away_Team           956 non-null    float64
 19  Rolling 5 Past H&A 1st Downs_Away_Team           938 non-null    float64
 20  Rolling 5 Past H&A 1st Downs Avg_Away_Team       938 non-null    float64
 21  Rolling 5 Past H&A Total Yards_Away_Team         938 non-null    float64
 22  Rolling 5 Past H&A Total Yards Avg_Away_Team     938 non-null    float64
 23  Rolling 5 Past H&A Yards per Pass_Away_Team      938 non-null    float64
 24  Rolling 5 Past H&A Yards per Pass Avg_Away_Team  938 non-null    float64
 25  Rolling 5 Past H&A Spread_Away_Team              942 non-null    float64
 26  Rolling 5 Past H&A Spread Avg_Away_Team          942 non-null    float64
 27  Previous H&A Ranking_Away_Team                   970 non-null    float64
 28  Previous H&A Ranking_Home_Team                   970 non-null    float64
 29  Home Team Ranking_x                              977 non-null    int64
 30  Away Team Ranking_x                              977 non-null    int64
 31  Rolling 5 Past H&A Conf T Losses_Home_Team       942 non-null    float64
 32  Rolling 5 Past H&A Conf T Losses_Away_Team       942 non-null    float64
 33  Rolling 5 Past H&A Season T Losses_Home_Team     942 non-null    float64
 34  Rolling 5 Past H&A Season T Losses_Away_Team     942 non-null    float64
 35  Away Score_x_x                                   976 non-null    float64
 36  Home Score_x_x                                   976 non-null    float64
 37  Home Team                                        977 non-null    object
 38  Away Team                                        977 non-null    object
 39  Year                                             977 non-null    int64
 40  Date                                             977 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(35), int64(3), object(2)
memory usage: 313.1+ KB

In [7]:
df3=df2.dropna()

In [9]:
df3.shape

(928, 41)

In [12]:
df3.isnull().sum().max()

0

In [13]:
df3.describe()

,Home Team Spread_x,Away Team Spread_x,Total_x,Rolling 5 Past H&A Score_Home_Team,Rolling 5 Past H&A Score Avg_Home_Team,Rolling 5 Past H&A 1st Downs_Home_Team,Rolling 5 Past H&A 1st Downs Avg_Home_Team,Rolling 5 Past H&A Total Yards_Home_Team,Rolling 5 Past H&A Total Yards Avg_Home_Team,Rolling 5 Past H&A Yards per Pass_Home_Team,...,Previous H&A Ranking_Home_Team,Home Team Ranking_x,Away Team Ranking_x,Rolling 5 Past H&A Conf T Losses_Home_Team,Rolling 5 Past H&A Conf T Losses_Away_Team,Rolling 5 Past H&A Season T Losses_Home_Team,Rolling 5 Past H&A Season T Losses_Away_Team,Away Score_x_x,Home Score_x_x,Year
count,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,...,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000,928.000000
mean,-2.789332,2.789332,51.568966,127.842672,25.568534,98.255388,19.651078,1863.168103,372.633621,36.118966,...,57.417026,58.510776,57.703664,11.232759,11.163793,13.346983,13.302802,24.303879,26.995690,2013.322198
std,13.285394,13.285394,8.111918,42.609400,8.521880,17.716224,3.543245,378.342550,75.668510,7.391478,...,44.560682,44.433919,44.457214,6.853036,6.794177,8.409957,8.275848,13.972399,13.461759,4.943768
min,-41.500000,-36.000000,27.000000,33.000000,6.600000,47.000000,9.400000,957.000000,191.400000,18.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2004.000000
25%,-12.500000,-6.500000,45.500000,99.000000,19.800000,87.000000,17.400000,1600.750000,320.150000,31.200000,...,10.000000,10.000000,10.000000,6.000000,5.000000,7.000000,7.000000,14.000000,17.000000,2009.000000
50%,-3.000000,3.000000,50.500000,124.000000,24.800000,97.000000,19.400000,1860.000000,372.000000,35.700000,...,99.000000,99.000000,99.000000,11.000000,11.000000,12.000000,13.000000,23.000000,27.000000,2013.500000
75%,6.500000,12.500000,56.500000,152.000000,30.400000,110.000000,22.000000,2110.250000,422.050000,40.800000,...,99.000000,99.000000,99.000000,16.000000,16.000000,19.000000,19.000000,34.000000,37.000000,2018.000000
max,36.000000,41.500000,82.500000,261.000000,52.200000,155.000000,31.000000,2987.000000,597.400000,64.300000,...,99.000000,99.000000,99.000000,35.000000,31.000000,40.000000,40.000000,72.000000,74.000000,2021.000000

In [19]:
Team_Matchups = pd.DataFrame(columns=df3['Home Team'].unique(),index=df3['Home Team'].unique())

In [20]:
Team_Matchups

,Alabama,LSU,Auburn,Vanderbilt,Arkansas,Mississippi State,South Carolina,Missouri,Ole Miss,Tennessee,Kentucky,Georgia,Texas A&M,Florida
Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LSU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Auburn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vanderbilt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arkansas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mississippi State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Carolina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Missouri,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ole Miss,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tennessee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kentucky,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas A&M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Florida,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
Row = 0
Column = 0

In [28]:
Teams=df3['Home Team'].unique()

In [29]:
Teams

array(['Alabama', 'LSU', 'Auburn', 'Vanderbilt', 'Arkansas',
       'Mississippi State', 'South Carolina', 'Missouri', 'Ole Miss',
       'Tennessee', 'Kentucky', 'Georgia', 'Texas A&M', 'Florida'],
      dtype=object)

In [30]:
Teams2=Teams

In [31]:
Teams2

array(['Alabama', 'LSU', 'Auburn', 'Vanderbilt', 'Arkansas',
       'Mississippi State', 'South Carolina', 'Missouri', 'Ole Miss',
       'Tennessee', 'Kentucky', 'Georgia', 'Texas A&M', 'Florida'],
      dtype=object)

In [32]:
Teams2[0]

'Alabama'

In [43]:
Team_Matchups.iloc[0,1] =1
Team_Matchups

,Alabama,LSU,Auburn,Vanderbilt,Arkansas,Mississippi State,South Carolina,Missouri,Ole Miss,Tennessee,Kentucky,Georgia,Texas A&M,Florida
Alabama,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LSU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Auburn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vanderbilt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arkansas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mississippi State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Carolina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Missouri,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ole Miss,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tennessee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kentucky,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas A&M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Florida,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df3[(df3['Home Team'] =='Alabama') & (df3['Away Team'] == 'LSU')]['Home Team'].count()

9

In [70]:
df3[(df3['Away Team'] =='Alabama') & (df3['Home Team'] == 'LSU')]['Home Team'].count()

9

In [74]:
df3[(df3['Home Team'] =='Alabama') & (df3['Away Team'] == 'LSU')]['Home Team'].count() + df3[(df3['Away Team'] =='Alabama') & (df3['Home Team'] == 'LSU')]['Home Team'].count()

18

In [98]:
Row = 0
Column= 0
Start = 0
Stop = 15

In [99]:
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [100]:
Row =1
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [101]:
Row =2
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [102]:
Row =3
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [103]:
Row =4
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [104]:
Row =5
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [105]:
Row =6
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [106]:
Row =7
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [107]:
Row =8
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [108]:
Row =9
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [109]:
Row =10
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [110]:
Row =11
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [111]:
Row =12
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [112]:
Row =13
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [113]:
Row =14
Column =0
while Column < Stop:
        Team_Matchups.iloc[Row,Column] = df3[(df3['Home Team'] ==Teams[Row]) & (df3['Away Team'] == Teams[Column])]['Home Team'].count() + df3[(df3['Away Team'] ==Teams[Row]) & (df3['Home Team'] == Teams[Column])]['Home Team'].count() 
        Column = Column + 1

IndexError: index 14 is out of bounds for axis 0 with size 14

In [ ]:
#Below shows the number of game matchups by teams. For example, there are 18 games of Alabama vs LSU.

In [114]:
Team_Matchups

,Alabama,LSU,Auburn,Vanderbilt,Arkansas,Mississippi State,South Carolina,Missouri,Ole Miss,Tennessee,Kentucky,Georgia,Texas A&M,Florida
Alabama,0,18,18,4,17,18,4,3,17,16,5,8,10,11
LSU,18,0,17,4,18,17,4,2,18,6,5,6,10,17
Auburn,18,17,0,4,17,17,8,2,17,6,5,19,10,4
Vanderbilt,4,4,4,0,4,5,17,10,16,17,18,15,3,18
Arkansas,17,18,17,4,0,18,10,8,18,5,4,6,9,6
Mississippi State,18,17,17,5,18,0,5,2,18,4,16,6,10,4
South Carolina,4,4,8,17,10,5,0,10,4,18,16,17,8,18
Missouri,3,2,2,10,8,2,10,0,2,10,10,10,5,10
Ole Miss,17,18,17,16,18,18,4,2,0,5,5,5,9,4
Tennessee,16,6,6,17,5,4,18,10,5,0,17,17,2,17
Kentucky,5,5,5,18,4,16,16,10,5,17,0,18,1,16
Georgia,8,6,19,15,6,6,17,10,5,17,18,0,1,16
Texas A&M,10,10,10,3,9,10,8,5,9,2,1,1,0,3
Florida,11,17,4,18,6,4,18,10,4,17,16,16,3,0

In [115]:
df3[(df3['Home Team'] =='Kentucky') & (df3['Away Team'] == 'Tennessee')]['Home Team'].count() + df3[(df3['Away Team'] =='Kentucky') & (df3['Home Team'] == 'Tennessee')]['Home Team'].count()

17

In [123]:
df3.dtypes

Home Team Spread_x                                        float64
Away Team Spread_x                                        float64
Total_x                                                   float64
Rolling 5 Past H&A Score_Home_Team                        float64
Rolling 5 Past H&A Score Avg_Home_Team                    float64
Rolling 5 Past H&A 1st Downs_Home_Team                    float64
Rolling 5 Past H&A 1st Downs Avg_Home_Team                float64
Rolling 5 Past H&A Total Yards_Home_Team                  float64
Rolling 5 Past H&A Total Yards Avg_Home_Team              float64
Rolling 5 Past H&A Yards per Pass_Home_Team               float64
Rolling 5 Past H&A Yards per Pass Avg_Home_Team           float64
Rolling 5 Past H&A Spread_Home_Team                       float64
Rolling 5 Past H&A Spread Avg_Home_Team                   float64
Rolling 5 Past H&A Spread Min_Home_Team                   float64
Rolling 5 Past H&A Score_Away_Team                        float64
Rolling 5 Past H&A Score Avg_Away_Team                    float64
Rolling 5 Past H&A Score Max_Away_Team                    float64
Rolling 3 Past H&A Score_Away_Team                        float64
Rolling 3 Past H&A Score Avg_Away_Team                    float64
Rolling 5 Past H&A 1st Downs_Away_Team                    float64
Rolling 5 Past H&A 1st Downs Avg_Away_Team                float64
Rolling 5 Past H&A Total Yards_Away_Team                  float64
Rolling 5 Past H&A Total Yards Avg_Away_Team              float64
Rolling 5 Past H&A Yards per Pass_Away_Team               float64
Rolling 5 Past H&A Yards per Pass Avg_Away_Team           float64
Rolling 5 Past H&A Spread_Away_Team                       float64
Rolling 5 Past H&A Spread Avg_Away_Team                   float64
Previous H&A Ranking_Away_Team                            float64
Previous H&A Ranking_Home_Team                            float64
Home Team Ranking_x                                         int64
Away Team Ranking_x                                         int64
Rolling 5 Past H&A Conf T Losses_Home_Team                float64
Rolling 5 Past H&A Conf T Losses_Away_Team                float64
Rolling 5 Past H&A Season T Losses_Home_Team              float64
Rolling 5 Past H&A Season T Losses_Away_Team              float64
Away Score_x_x                                            float64
Home Score_x_x                                            float64
Home Team                                                  object
Away Team                                                  object
Year                                                        int64
Date                                               datetime64[ns]
dtype: object

In [155]:

for i in df3.columns:
    if df3[i].dtypes == 'float64':
        mean = df3[i].mean()
        std =df3[i].std()
        lower = mean + (-3 *std)
        upper = mean + (3*std)
        count = df3[(df3[i] > lower) & (df3[i] < upper)]['Home Team'].count()
        print('Feature:',i, "\n"' Rows: ', count,' Mean: ', mean,"\n" ' Std: ', std, ' Upper: ', upper,' Lower: ', lower, )

Feature: Home Team Spread_x
 Rows:  928  Mean:  -2.789331896551724
 Std:  13.285393768309849  Upper:  37.06684940837783  Lower:  -42.64551320148127
Feature: Away Team Spread_x
 Rows:  928  Mean:  2.789331896551724
 Std:  13.285393768309849  Upper:  42.64551320148127  Lower:  -37.06684940837783
Feature: Total_x
 Rows:  922  Mean:  51.56896551724138
 Std:  8.111918476332402  Upper:  75.90472094623858  Lower:  27.233210088244174
Feature: Rolling 5 Past H&A Score_Home_Team
 Rows:  926  Mean:  127.84267241379311
 Std:  42.609400158266304  Upper:  255.67087288859202  Lower:  0.014471938994205402
Feature: Rolling 5 Past H&A Score Avg_Home_Team
 Rows:  926  Mean:  25.568534482758622
 Std:  8.521880031653271  Upper:  51.13417457771844  Lower:  0.002894387798807685
Feature: Rolling 5 Past H&A 1st Downs_Home_Team
 Rows:  925  Mean:  98.25538793103448
 Std:  17.716223863541337  Upper:  151.4040595216585  Lower:  45.106716340410465
Feature: Rolling 5 Past H&A 1st Downs Avg_Home_Team
 Rows:  925  Mean:  19.651077586206878
 Std:  3.5432447727082756  Upper:  30.280811904331706  Lower:  9.02134326808205
Feature: Rolling 5 Past H&A Total Yards_Home_Team
 Rows:  928  Mean:  1863.1681034482758
 Std:  378.34254978703456  Upper:  2998.1957528093794  Lower:  728.1404540871722
Feature: Rolling 5 Past H&A Total Yards Avg_Home_Team
 Rows:  928  Mean:  372.63362068965563
 Std:  75.66850995740693  Upper:  599.6391505618765  Lower:  145.62809081743484
Feature: Rolling 5 Past H&A Yards per Pass_Home_Team
 Rows:  924  Mean:  36.11896551724143
 Std:  7.391477804083528  Upper:  58.293398929492014  Lower:  13.944532104990845
Feature: Rolling 5 Past H&A Yards per Pass Avg_Home_Team
 Rows:  924  Mean:  7.223793103448271
 Std:  1.4782955608167048  Upper:  11.658679785898386  Lower:  2.788906420998156
Feature: Rolling 5 Past H&A Spread_Home_Team
 Rows:  926  Mean:  1.2952586206896552
 Std:  48.23283938549076  Upper:  145.99377677716194  Lower:  -143.40325953578264
Feature: Rolling 5 Past H&A Spread Avg_Home_Team
 Rows:  926  Mean:  0.25905172413793115
 Std:  9.646567877098157  Upper:  29.1987553554324  Lower:  -28.68065190715654
Feature: Rolling 5 Past H&A Spread Min_Home_Team
 Rows:  928  Mean:  -11.655711206896552
 Std:  10.70151315206914  Upper:  20.448828249310868  Lower:  -43.760250663103974
Feature: Rolling 5 Past H&A Score_Away_Team
 Rows:  924  Mean:  128.4019396551724
 Std:  41.249354563400296  Upper:  252.1500033453733  Lower:  4.653875964971519
Feature: Rolling 5 Past H&A Score Avg_Away_Team
 Rows:  924  Mean:  25.68038793103452
 Std:  8.249870912680052  Upper:  50.43000066907467  Lower:  0.9307751929943642
Feature: Rolling 5 Past H&A Score Max_Away_Team
 Rows:  928  Mean:  40.53879310344828
 Std:  11.295033488113296  Upper:  74.42389356778816  Lower:  6.653692639108392
Feature: Rolling 3 Past H&A Score_Away_Team
 Rows:  925  Mean:  77.33728448275862
 Std:  28.481895495964416  Upper:  162.7829709706519  Lower:  -8.108402005134636
Feature: Rolling 3 Past H&A Score Avg_Away_Team
 Rows:  925  Mean:  25.77909482758623
 Std:  9.493965165321475  Upper:  54.26099032355066  Lower:  -2.7028006683781918
Feature: Rolling 5 Past H&A 1st Downs_Away_Team
 Rows:  925  Mean:  98.62931034482759
 Std:  16.979474974145973  Upper:  149.5677352672655  Lower:  47.69088542238967
Feature: Rolling 5 Past H&A 1st Downs Avg_Away_Team
 Rows:  925  Mean:  19.725862068965508
 Std:  3.395894994829192  Upper:  29.913547053453087  Lower:  9.538177084477931
Feature: Rolling 5 Past H&A Total Yards_Away_Team
 Rows:  926  Mean:  1867.9762931034484
 Std:  366.49982005415575  Upper:  2967.4757532659155  Lower:  768.4768329409812
Feature: Rolling 5 Past H&A Total Yards Avg_Away_Team
 Rows:  926  Mean:  373.59525862069063
 Std:  73.29996401083105  Upper:  593.4951506531838  Lower:  153.6953665881975
Feature: Rolling 5 Past H&A Yards per Pass_Away_Team
 Rows:  925  Mean:  36.25118534482761
 Std:  7.363670603977628  Upper:  58.34219715676049  Lower:  14.160173532894728
Feature: Rolling 5 Past H&A Yards per Pass Avg_Away_Team
 Rows:  925  Mean:  7.2502370689655296
 Std:  1.4727341207955253  Upper:  11.668439431352105  Lower:  2.8320347065789537
Feature: Rolling 5 Past H&A Spread_Away_Team
 Rows:  927  Mean:  -2.0420258620689653
 Std:  48.4307506265125  Upper:  143.25022601746855  Lower:  -147.33427774160646
Feature: Rolling 5 Past H&A Spread Avg_Away_Team
 Rows:  927  Mean:  -0.4084051724137935
 Std:  9.6861501253025  Upper:  28.650045203493708  Lower:  -29.466855548321295
Feature: Previous H&A Ranking_Away_Team
 Rows:  928  Mean:  58.734913793103445
 Std:  44.29513633952005  Upper:  191.62032281166358  Lower:  -74.15049522545671
Feature: Previous H&A Ranking_Home_Team
 Rows:  928  Mean:  57.41702586206897
 Std:  44.56068200542936  Upper:  191.09907187835705  Lower:  -76.26502015421913
Feature: Rolling 5 Past H&A Conf T Losses_Home_Team
 Rows:  927  Mean:  11.232758620689655
 Std:  6.853036094218637  Upper:  31.791866903345564  Lower:  -9.326349661966255
Feature: Rolling 5 Past H&A Conf T Losses_Away_Team
 Rows:  928  Mean:  11.163793103448276
 Std:  6.794177297051579  Upper:  31.54632499460301  Lower:  -9.218738787706462
Feature: Rolling 5 Past H&A Season T Losses_Home_Team
 Rows:  927  Mean:  13.34698275862069
 Std:  8.409956571065662  Upper:  38.57685247181767  Lower:  -11.882886954576293
Feature: Rolling 5 Past H&A Season T Losses_Away_Team
 Rows:  926  Mean:  13.30280172413793
 Std:  8.275847855645493  Upper:  38.130345291074406  Lower:  -11.524741842798546
Feature: Away Score_x_x
 Rows:  927  Mean:  24.30387931034483
 Std:  13.972399439601123  Upper:  66.2210776291482  Lower:  -17.613319008458543
Feature: Home Score_x_x
 Rows:  927  Mean:  26.995689655172413
 Std:  13.461759445821063  Upper:  67.3809679926356  Lower:  -13.389588682290778

[928,
 928,
 922,
 926,
 926,
 925,
 925,
 928,
 928,
 924,
 924,
 926,
 926,
 928,
 924,
 924,
 928,
 925,
 925,
 925,
 925,
 926,
 926,
 925,
 925,
 927,
 927,
 928,
 928,
 927,
 928,
 927,
 926,
 927,
 927]